<?php
$form = $this->tasksForm;
$form->prepare();

// Assuming the "contact/process" route exists...
$form->setAttribute('action', $this->url('home-post'));

// Set the method attribute for the form
$form->setAttribute('method', 'post');

// Get the form label plugin
$formLabel = $this->plugin('formLabel');

// Render the opening tag
echo $this->form()->openTag($form);
?>

<div class="form_element">
<?php
    $message = $form->get('task');
    echo $formLabel->openTag() . $message->getOption('label');
    echo $this->formTel($message);
    echo $this->formElementErrors($message);
    echo $formLabel->closeTag();
?></div>

<?php echo $this->formElement($form->get('submit')) ?>

<?php echo $this->form()->closeTag() ?>